from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List
from app.database.database import get_db
from app.models import models
from app.schemas import schemas

# We use APIRouter to keep our code clean instead of putting all routes in main.py
router = APIRouter(prefix="/projects", tags=["Projects"])

@router.post("/", response_model=schemas.ProjectResponse)
def create_project(project: schemas.ProjectCreate, db: Session = Depends(get_db)):
    """
    Creates a new project.
    Validates that the user exists first.
    """
    # 1. Check if user exists
    user = db.query(models.User).filter(models.User.id == project.user_id).first()
    if not user:
        # Beginner-friendly error!
        raise HTTPException(status_code=404, detail="Whoops! We cannot create a project for a user that doesn't exist.")
        
    # 2. Convert Pydantic Schema to SQLAlchemy Model
    new_project = models.Project(**project.model_dump())
    
    # 3. Add to Database and Commit Transaction
    db.add(new_project)
    db.commit()
    db.refresh(new_project) # Get the new ID generated by PostgreSQL
    
    return new_project

@router.get("/", response_model=List[schemas.ProjectResponse])
def get_projects(db: Session = Depends(get_db)):
    """
    Returns a list of all projects in the database.
    """
    return db.query(models.Project).all()

@router.get("/{project_id}", response_model=schemas.ProjectResponse)
def get_project(project_id: int, db: Session = Depends(get_db)):
    """
    Gets a single project by its ID.
    """
    project = db.query(models.Project).filter(models.Project.id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail=f"Project with ID {project_id} was not found.")
    return project

@router.delete("/{project_id}")
def delete_project(project_id: int, db: Session = Depends(get_db)):
    project = db.query(models.Project).filter(models.Project.id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found.")
    
    # Thanks to ON DELETE CASCADE, this will also delete assets, sprites, and frames!
    db.delete(project)
    db.commit()
    return {"message": "Project deleted successfully"}
